packages:
  - apps/*
  - packages/*

saveExact: true
engineStrict: true
packageManagerStrict: true
packageManagerStrictVersion: true
managePackageManagerVersions: false
strictPeerDependencies: true
strictDepBuilds: true
sideEffectsCache: false
storeDir: .cache/pnpm
allowBuilds:
  better-sqlite3: true
  esbuild: true
